# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"5\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"4\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"@\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"9\n\x15ValidateTokenResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xca\x01\n\x0b\x41uthService\x12;\n\x08Register\x12\x15.auth.RegisterRequest\x1a\x16.auth.RegisterResponse\"\x00\x12\x32\n\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\"\x00\x12J\n\rValidateToken\x12\x1a.auth.ValidateTokenRequest\x1a\x1b.auth.ValidateTokenResponse\"\x00\x42\x07Z\x05/authb\x06proto3')



_REGISTERREQUEST = DESCRIPTOR.message_types_by_name['RegisterRequest']
_REGISTERRESPONSE = DESCRIPTOR.message_types_by_name['RegisterResponse']
_LOGINREQUEST = DESCRIPTOR.message_types_by_name['LoginRequest']
_LOGINRESPONSE = DESCRIPTOR.message_types_by_name['LoginResponse']
_VALIDATETOKENREQUEST = DESCRIPTOR.message_types_by_name['ValidateTokenRequest']
_VALIDATETOKENRESPONSE = DESCRIPTOR.message_types_by_name['ValidateTokenResponse']
RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)

RegisterResponse = _reflection.GeneratedProtocolMessageType('RegisterResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERRESPONSE,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.RegisterResponse)
  })
_sym_db.RegisterMessage(RegisterResponse)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.LoginRequest)
  })
_sym_db.RegisterMessage(LoginRequest)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESPONSE,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.LoginResponse)
  })
_sym_db.RegisterMessage(LoginResponse)

ValidateTokenRequest = _reflection.GeneratedProtocolMessageType('ValidateTokenRequest', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATETOKENREQUEST,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.ValidateTokenRequest)
  })
_sym_db.RegisterMessage(ValidateTokenRequest)

ValidateTokenResponse = _reflection.GeneratedProtocolMessageType('ValidateTokenResponse', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATETOKENRESPONSE,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.ValidateTokenResponse)
  })
_sym_db.RegisterMessage(ValidateTokenResponse)

_AUTHSERVICE = DESCRIPTOR.services_by_name['AuthService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\005/auth'
  _REGISTERREQUEST._serialized_start=20
  _REGISTERREQUEST._serialized_end=73
  _REGISTERRESPONSE._serialized_start=75
  _REGISTERRESPONSE._serialized_end=127
  _LOGINREQUEST._serialized_start=129
  _LOGINREQUEST._serialized_end=179
  _LOGINRESPONSE._serialized_start=181
  _LOGINRESPONSE._serialized_end=245
  _VALIDATETOKENREQUEST._serialized_start=247
  _VALIDATETOKENREQUEST._serialized_end=284
  _VALIDATETOKENRESPONSE._serialized_start=286
  _VALIDATETOKENRESPONSE._serialized_end=343
  _AUTHSERVICE._serialized_start=346
  _AUTHSERVICE._serialized_end=548
# @@protoc_insertion_point(module_scope)
